# Read the data

In [ ]:
!unzip /content/drive/MyDrive/enronsent.zip -d /content/enronsent

Archive:  /content/drive/MyDrive/enronsent.zip
  inflating: /content/enronsent/enronsent01  
  inflating: /content/enronsent/enronsent02  
  inflating: /content/enronsent/enronsent03  
  inflating: /content/enronsent/enronsent04  
  inflating: /content/enronsent/enronsent05  
  inflating: /content/enronsent/enronsent06  
  inflating: /content/enronsent/enronsent07  
  inflating: /content/enronsent/enronsent08  
  inflating: /content/enronsent/enronsent09  
  inflating: /content/enronsent/enronsent10  
  inflating: /content/enronsent/enronsent11  
  inflating: /content/enronsent/enronsent12  
  inflating: /content/enronsent/enronsent13  
  inflating: /content/enronsent/enronsent14  
  inflating: /content/enronsent/enronsent15  
  inflating: /content/enronsent/enronsent00  


In [ ]:
import os
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
def load_data(data_dir):
    sentences = []

    # Iterate through all text files in the data directory
    for file_name in os.listdir(data_dir):
        file_path = os.path.join(data_dir, file_name)
        if os.path.isfile(file_path):
            with open(file_path, 'r', encoding='utf-8') as file:
                text = file.read()
                sentences.append(text)

    return sentences

data_dir = '/content/enronsent'
sentences = load_data(data_dir)

In [ ]:
print(len(sentences))
#her i split text to train the model for only one text then i use all the data as usual that cell for only tring one text
x_train = sentences[:11]
print (len(x_train))
x_val = sentences[11:]
print (len(x_val))

16
11
5


In [ ]:
#x_train[0]

# Tokenization and preprocessing

In [ ]:
import nltk
from nltk.corpus import stopwords
import re

nltk.download('stopwords')

def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    filtered_sentences = []

    if isinstance(text, str):
        # Single sentence
        words = text.split()
        filtered_words = [word for word in words if len(word) > 2 and not re.search(r'\d', word) and word.lower() not in stop_words]
        filtered_sentence = ' '.join(filtered_words)
        return filtered_sentence

    elif isinstance(text, list):
        # List of sentences
        for sentence in text:
            words = sentence.split()
            filtered_words = [word for word in words if len(word) > 2 and not re.search(r'\d', word) and word.lower() not in stop_words]
            filtered_sentence = ' '.join(filtered_words)
            filtered_sentences.append(filtered_sentence)
        return filtered_sentences

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
# Convert the list of sentences to a single string
# text = ' '.join(sentences)
# # Remove stop words from the text
# filtered_text = remove_stopwords(text)
# Remove stop words from the text
remove_stopwords = remove_stopwords(sentences)
tokenizer = Tokenizer()
tokenizer.fit_on_texts(remove_stopwords)

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(remove_stopwords)
word_to_index = tokenizer.word_index
index_to_word = {index: word for word, index in word_to_index.items()}

In [ ]:
len(index_to_word)
#85945
#64134
#64056

64056

In [ ]:
index_to_word

{1: 'please',
 2: 'would',
 3: 'enron',
 4: 'thanks',
 5: 'know',
 6: 'get',
 7: 'need',
 8: 'gas',
 9: 'com',
 10: 'power',
 11: 'let',
 12: 'time',
 13: 'e',
 14: 'like',
 15: 'one',
 16: 'may',
 17: 'call',
 18: 'new',
 19: 'energy',
 20: 'also',
 21: 'pm',
 22: 'said',
 23: 'deal',
 24: 'could',
 25: 'see',
 26: 'you',
 27: 'meeting',
 28: 'think',
 29: 'jeff',
 30: 'information',
 31: 'attached',
 32: 'company',
 33: 'going',
 34: 'day',
 35: 'want',
 36: 'back',
 37: 'make',
 38: 'week',
 39: 'work',
 40: 'market',
 41: 'california',
 42: "i'm",
 43: 'best',
 44: 'state',
 45: 'last',
 46: 'good',
 47: 'questions',
 48: 'it',
 49: 'business',
 50: 'agreement',
 51: 'email',
 52: 'contract',
 53: 'next',
 54: 'price',
 55: 'today',
 56: 'mail',
 57: 'take',
 58: 'well',
 59: 'group',
 60: 'year',
 61: 'message',
 62: 'two',
 63: 'help',
 64: 'trading',
 65: 'review',
 66: 'forward',
 67: 'send',
 68: 'file',
 69: 'office',
 70: 'use',
 71: 'mark',
 72: 'still',
 73: 'following',
 

#  Preparing Data by Split sentences into fixed time steps

In [ ]:
#for getting word embedding vector such
max_sequence_length = 1
sequences = tokenizer.texts_to_sequences(sentences)
X = []
y = []
for sequence in sequences:
    for i in range(len(sequence) - max_sequence_length):
        X.append(sequence[i:i+max_sequence_length])
        y.append(sequence[i+max_sequence_length])
X = np.array(X)
y = np.array(y)

In [ ]:
X

array([[ 543],
       [2694],
       [ 589],
       ...,
       [ 268],
       [ 179],
       [ 877]])

In [ ]:
X.shape
#(5616129, 10)

(5120754, 1)

In [ ]:
y.shape
#(5616129,)

(5120754,)

# Convert the text data into sequences of word indices

In [ ]:
vocab_size = len(word_to_index) + 1  # +1 for padding
X = pad_sequences(X, maxlen=max_sequence_length, padding='pre')
y = np.expand_dims(y, axis=1)

In [ ]:
X.shape
#(5616129, 10)

(5120754, 1)

In [ ]:
X

array([[ 543],
       [2694],
       [ 589],
       ...,
       [ 268],
       [ 179],
       [ 877]], dtype=int32)

In [ ]:
y.shape
#(5616129, 1)

(5120754, 1)

In [ ]:
y

array([[2694],
       [ 589],
       [ 691],
       ...,
       [ 179],
       [ 877],
       [ 438]])

# Download a pretrained word2vec model

In [ ]:
import gensim.downloader as api
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# Download the pre-trained 'glove-wiki-gigaword-100' model
word2vec_model = api.load('glove-wiki-gigaword-100')

[=================================================-] 99.2% 127.0/128.1MB downloaded


# Divide data into training and validation sets for Training

In [ ]:
split_index = int(0.8 * len(X))
X_train, X_val = X[:split_index], X[split_index:]
y_train, y_val = y[:split_index], y[split_index:]

In [ ]:
X_train.shape

(4096603, 1)

In [ ]:
X_val.shape

(1024151, 1)

In [ ]:
y_train.shape

(4096603, 1)

In [ ]:
y_val.shape

(1024151, 1)

In [ ]:
X_train

array([[ 543],
       [2694],
       [ 589],
       ...,
       [5369],
       [ 589],
       [2383]], dtype=int32)

# Create the LSTM model

In [ ]:
embedding_dim = word2vec_model.vector_size
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_sequence_length))
model.add(LSTM(units=128))
model.add(Dense(units=vocab_size, activation='softmax'))

In [ ]:
# Use the word2vec model as the embedding layer
embedding_matrix = np.zeros((vocab_size, embedding_dim))
for word, index in word_to_index.items():
    if word in word2vec_model:
        embedding_matrix[index] = word2vec_model[word]

In [ ]:
model.layers[0].set_weights([embedding_matrix])
model.layers[0].trainable = False

In [ ]:
model.summary()

Model: "sequential_34"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 1, 100)            6405700   
                                                                 
 lstm_2 (LSTM)               (None, 128)               117248    
                                                                 
 dense_2 (Dense)             (None, 64057)             8263353   
                                                                 
Total params: 14,786,301
Trainable params: 8,380,601
Non-trainable params: 6,405,700
_________________________________________________________________


# Train the LSTM model

In [ ]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=10, batch_size=128)

In [ ]:
from keras.models import load_model, save_model

# Save the model
# save_model(model, '/content/drive/MyDrive/NLP_1.h5')

In [ ]:
# Load the model
model = load_model('/content/drive/MyDrive/NLP_1.h5')

In [ ]:
def predict_next_word(model, word):
    # Predict the next word given a word
    # input_sequence = pad_sequences([[word_to_index[word]]], maxlen=max_sequence_length, padding='pre')
    # print(np.array(input_sequence[0]))
    predicted_index = np.argmax(model.predict(np.array([word_to_index[word]])), axis=-1)[0]
    predicted_word = index_to_word[predicted_index]
    return predicted_word

# Testing loop

In [ ]:
def sentence_autocomplete():
    # Load the trained LSTM model
    # model = Sequential()
    # Add layers to the model (similar to training code)

    while True:
        sentence = input("Enter the next word (-1 to terminate): ")
        if sentence == '-1':
            break
        words = sentence.split()
        while True:
            word = words[-1]
            # print(word)
            predicted_word = index_to_word[np.argmax(model.predict([word_to_index[word]]), axis=-1)[0]]
            print("Is your next word:", predicted_word)
            response = input("Enter 'Yes' if correct, (-1 to terminate) or the correct word: ")
            if response.lower() == 'yes':
                words.append(predicted_word)
                # if i < len(words) - 1:
                #     continue
                # else:
                #     break
            elif response == '-1':
                break
            else:
                words.append(response)
        final_sentence = ' '.join(words)
        if response == '-1':
            print("Your final sentence is:", final_sentence)
            break
        print("Your final sentence is:", final_sentence)

# Call the testing loop for three different sentences
for _ in range(2):
    sentence_autocomplete()

Enter the next word (-1 to terminate): my
1/1 [==============================] - 0s 358ms/step
Is your next word: assistant
Enter 'Yes' if correct, (-1 to terminate) or the correct word: yes
1/1 [==============================] - 0s 47ms/step
Is your next word: to
Enter 'Yes' if correct, (-1 to terminate) or the correct word: is
1/1 [==============================] - 0s 31ms/step
Is your next word: the
Enter 'Yes' if correct, (-1 to terminate) or the correct word: yes
1/1 [==============================] - 0s 30ms/step
Is your next word: following
Enter 'Yes' if correct, (-1 to terminate) or the correct word: best
1/1 [==============================] - 0s 32ms/step
Is your next word: jeff
Enter 'Yes' if correct, (-1 to terminate) or the correct word: -1
Your final sentence is: my assistant is the best
Enter the next word (-1 to terminate): hi
1/1 [==============================] - 0s 46ms/step
Is your next word: chris
Enter 'Yes' if correct, (-1 to terminate) or the correct word: yes
1